### ISSUE TITLE
Resize makes main window very small

### ISSUE THREAD

**Issue by remembertoremind** [saysjonathan/dwm.tmux#2]
Hi! Love this config - thanks for making it!

When starting a new window Meta+w the text "'tmux resize-pane -t :.0 -x "$(echo "319/2/1" | bc)"' returned 1" appears in the new window and ctrl+c or enter is needed to get back to the prompt. Moreover, windows are rearranged so the main window is like 1/4 of the screen. If I change the layout with main having 50% of the sceen and create a new window it defaults back to 1/4 for main.

Not sure how to solve this, but I'll see if I can find a solution. Just wanted you and others to know :)

EDIT: Killing windows (Meta+c) has the same effect: Prints the same text and rearranges the layout.

EDIT2: The behavior of how much width the main window has changes with the size of the terminal. One terminal on 1920x1200 has the 1/4th effect, but a flowting square terminal will make the main 50% of the width in most cases. On ttys its more like 1/3rd of the screen that's allocated to the main window.

**Comment by saysjonathan** [comment]
@remembertoremind I'm sorry for the delay. I just merged in a #3 that swtiches from using `bc` calculations to percentages for splits. I believe this may resolve your issue. Can you try the current master and see how that works?

**Comment by remembertoremind** [comment]
Wow! I thought you had given up. This works and it works _really_ well.. I might change some keys to fit my current dwm layout, but apart from that, it's all good. Thank you soo much! :D

**Comment by saysjonathan** [comment]
Haven't given up yet! Tag `0.1.0` (or `latest`) supports custom keybindings and works through tmux 3.1c. 3.2 changes some config parsing stuff and I'm working on support now. I'm also hoping to get this closer to base dwm feature-wise. I'm experimenting around `dmenu` and other layouts.

Feel free to drop in any other feedback!

**Comment by remembertoremind** [comment]
Sounds great! :) I'll be checking in from time to time.

**Comment by dv-blk** [comment]
Hello! I managed to fix this by changing https://github.com/saysjonathan/dwm.tmux/blob/master/bin/dwm.tmux#L86 to:
```
command=$1;shift
window_panes=$(tmux list-panes | wc -l | xargs)
mfact=$(tmux showenv mfact | awk -F= '{print $2}')
killlast=$2
```

I haven't bothered with `killlast` yet, but i'm sure it's easy enough to figure out. But the current `tmux display -p` command needs formatting to strip newlines etc for it to work again.

Thanks for this repo!
