### ISSUE TITLE
Choosing new master is master exits

### ISSUE THREAD

**Issue by remembertoremind** [saysjonathan/dwm.tmux#4]
Hi!

When I have e.g. 4 panes open, and I type `exit` in the master, the 3 remaining panes are all placed horizontally instead of making one of the other panes a new master. If the master is closed with `alt+c` it behaves as `dwm` and a new master is chosen.

**Comment by saysjonathan** [comment]
I just a pushed a new commit to master that should resolve this. It uses the hooks facility to run the retiling command when a pane exits. Can you make sure that works for you?

If you haven't switched to using master yet can you also let me know how that goes? I have a relatively powerful setup right now, so any additional information about the performance and setup process would be helpful.
